version: "3.4"

volumes:
  jenkins:
    name: 'jenkins'
   
services:

  jenkins:
    image: jenkins/jenkins:lts
    user: jenkins
    volumes:
      - jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      JENKINS_HOST_HOME: "/data/jenkins"
    ports:
      - 8180:8080
      - 5001:5000
      - 50000:50000
    deploy:
      endpoint_mode: vip
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
          condition: on-failure
      replicas: 1
      placement:
        constraints:
          - node.labels.role==devops
